import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;

public class GamePanel extends JPanel implements KeyListener {
    private Ball ball;
    private Paddle paddle;
    private ArrayList<Brick> blocks = new ArrayList<>();
    private Image image;
    private Thread thread;
    private boolean pause = false;

    public GamePanel() {
        resetScene();
    }

    public void paint(Graphics g) {
        this.ball.paint(g);
        this.paddle.paint(g);
        blocks.forEach(block -> block.paint(g));
        g.drawImage(image, 0, 0, this);
    }

    private void resetScene() {
        ball = new Ball();
        paddle = new Paddle();
        blocks.add(new Brick(10,10));

        addKeyListener(this);
        setFocusable(true);
    }

    public void update() {

        ball.x += ball.xDirection;
        ball.y += ball.yDirection;

        if(ball.x > (getWidth() - 25) || ball.x < 0) {
            ball.xDirection *= -1;
        }

        if(ball.y < 0 || ball.intersects(paddle)) {
            ball.yDirection *= -1;
        }

        if (ball.y > getHeight()) {
            thread = null;
            // Loose or game over
            resetScene();
        }

        blocks.forEach(block -> {
            if (ball.intersects(block) && !block.destroyed) {
                block.destroyed = true;
                ball.yDirection *= -1;
            }
        });

        repaint();
    }

    public void pause() {
        if (!pause) {
            ball.xDirection = 0;
            ball.yDirection = 0;
            pause = true;

        } else {
            ball.xDirection = -1;
            ball.yDirection = -1;
            pause = false;
        }
    }



    // MARK: Autogenerated methods for KeyListener

    @Override
    public void keyTyped(KeyEvent e) {

    }


    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_SPACE && thread == null) {
            System.out.println("Space");
            thread = new Thread(() -> {
                while (true) {
                    update();
                    try {
                        Thread.sleep(10);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
            });
            thread.start();
        }

        if (e.getKeyCode() == KeyEvent.VK_RIGHT && paddle.x < (getWidth() - paddle.width)) {
            paddle.x += 15;
            update();
        }

        if (e.getKeyCode() == KeyEvent.VK_LEFT && paddle.x > 0) {
            paddle.x -= 15;
            update();
        }

        if (e.getKeyCode() == KeyEvent.VK_P) {
            pause();
        }
    }




    @Override
    public void keyReleased(KeyEvent e) {

    }
}
